---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-svc
  namespace: server-svc
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::357171621133:role/devcql-cloudquicklabs-eks-server-svc
