---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: server-svc
  namespace: server-svc
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: server-svc
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: server-svc
              weight: 1
