apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: default
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
    expireAfter: Never
  limits:
    cpu: "10"
  template:
    metadata:
      # Labels are arbitrary key-values that are applied to all nodes
      labels:
        eks-immersion-team: my-team
    spec:
      # References cloud provider-specific custom resource, see your cloud provider specific documentation
      nodeClassRef:
        name: default

      # Requirements that constrain the parameters of provisioned nodes.
      # These requirements are combined with pod.spec.affinity.nodeAffinity rules.
      # Operators { In, NotIn } are supported to enable including or excluding values
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
          operator: In
          values: ["on-demand"]

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-karpenter-demo"
  securityGroupSelectorTerms:
  - tags:
      alpha.eksctl.io/cluster-name: karpenter-demo
  subnetSelectorTerms:
  - tags:
      alpha.eksctl.io/cluster-name: karpenter-demo
  tags:
    intent: apps
    managed-by: karpenter