---
apiVersion: v1
kind: Pod
metadata:
  name: client-svc
  namespace: client-svc
  labels:
    app: client-svc
spec:
  serviceAccountName: client-svc
  containers:
    - name: ubuntu
      image: alpine/curl:8.2.1
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
